import json
from .db import get_connection


def init_audit_table():
    conn = get_connection()
    conn.execute(
        """
        CREATE TABLE IF NOT EXISTS audit_log (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            customer_id TEXT NOT NULL,
            entry_json TEXT NOT NULL,
            human_decision TEXT,
            created_at TEXT NOT NULL,
            source_id TEXT UNIQUE
        )
        """
    )
    conn.commit()
    conn.close()


def save_audit_entry(entry_dict: dict, source_id: str | None = None):
    required_fields = {"customer_id", "timestamp"}
    if not required_fields.issubset(entry_dict):
        return

    conn = get_connection()
    conn.execute(
        """
        INSERT INTO audit_log (customer_id, entry_json, human_decision, created_at, source_id)
        VALUES (%s, %s, %s, %s, %s)
        ON CONFLICT (source_id) DO NOTHING
        """,
        (
            entry_dict["customer_id"],
            json.dumps(entry_dict),
            entry_dict.get("human_decision"),
            entry_dict["timestamp"],
            source_id,
        ),
    )
    conn.commit()
    conn.close()


def migrate_resolved_reviews():
    conn = get_connection()
    rows = conn.execute(
        "SELECT review_id, state_json, created_at FROM pending_reviews WHERE status = 'resolved'"
    ).fetchall()
    conn.close()

    for row in rows:
        state = json.loads(row["state_json"])
        attempts = state.get("draft_attempts") or []
        final_reply = state.get("final_reply", "")
        entry = {
            "timestamp": row["created_at"],
            "customer_id": state.get("customer_id", ""),
            "complaint_text": state.get("complaint_text", ""),
            "classification": state.get("classification"),
            "risk_assessment": state.get("risk_assessment"),
            "draft_attempts": attempts,
            "guardrail_results": state.get("guardrail_results", []),
            "human_decision": state.get("human_decision"),
            "final_reply": final_reply,
        }
        save_audit_entry(entry, source_id=row["review_id"])


def get_all_resolved(limit: int = 50):
    limit = max(1, min(limit, 200))
    init_audit_table()
    migrate_resolved_reviews()
    conn = get_connection()
    rows = conn.execute(
        "SELECT entry_json FROM audit_log ORDER BY created_at DESC, id DESC LIMIT %s",
        (limit,),
    ).fetchall()
    conn.close()
    return [json.loads(row["entry_json"]) for row in rows]
